import { PeaType, SunSize } from './plantsTypes.js'

export const PLANT_DETAILS = {
  peashooter: {
    tag: 'plants/day',
    index: 0,
    countSeeds: 8,
    cost: 4,
    toughness: 300,
    recharge: 7500,
    defaultLoaded: false,
    attack: {
      type: 'shoot',
      peaType: PeaType.Pea,
      fireRate: 1400,
      maxRange: 9,
    },
    sunProduction: null,
  },
  sunflower: {
    tag: 'plants/day',
    index: 1,
    countSeeds: 8,
    cost: 2,
    toughness: 300,
    recharge: 7500,
    defaultLoaded: true,
    attack: null,
    sunProduction: {
      rate: 24000,
      size: SunSize.Normal,
    },
  },
  'cherry-bomb': {
    tag: 'plants/day',
    index: 2,
    countSeeds: 8,
    cost: 6,
    toughness: 300,
    recharge: 50000,
    defaultLoaded: false,
    attack: {
      type: 'explode',
      range: 3,
    },
    sunProduction: null,
  },
  'wall-nut': {
    tag: 'plants/day',
    index: 3,
    countSeeds: 8,
    cost: 2,
    toughness: 4000,
    recharge: 30000,
    defaultLoaded: false,
    attack: null,
    sunProduction: null,
  },
  potatomine: {
    tag: 'plants/day',
    index: 4,
    countSeeds: 8,
    cost: 1,
    toughness: 300,
    recharge: 30000,
    defaultLoaded: false,
    attack: {
      type: 'explode',
      range: 1,
    },
    sunProduction: null,
  },
  snowpea: {
    tag: 'plants/day',
    index: 5,
    countSeeds: 8,
    cost: 7,
    toughness: 300,
    recharge: 7500,
    defaultLoaded: false,
    attack: {
      type: 'shoot',
      peaType: PeaType.Snowpea,
      fireRate: 1400,
      maxRange: 9,
    },
    sunProduction: null,
  },
  chomper: {
    tag: 'plants/day',
    index: 6,
    countSeeds: 8,
    cost: 6,
    toughness: 300,
    recharge: 7500,
    defaultLoaded: false,
    attack: {
      type: 'eat',
    },
    sunProduction: null,
  },
  repeater: {
    tag: 'plants/day',
    index: 7,
    countSeeds: 8,
    cost: 8,
    toughness: 300,
    recharge: 7500,
    defaultLoaded: false,
    attack: {
      type: 'shoot',
      peaType: PeaType.Pea,
      fireRate: 700,
      maxRange: 9,
    },
    sunProduction: null,
  },
} as const
